name: profile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.jpg
    - assets/images/posapp.png
    - assets/images/katalog.png
    - assets/images/carelink.png
    - assets/images/payroll.png
    - assets/images/todolist.png
